FROM mcr.microsoft.com/playwright:v1.57.0-noble

ARG JUST_VERSION=1.47.1
ARG PNPM_VERSION=10.30.3

ADD https://github.com/casey/just/releases/download/${JUST_VERSION}/just-${JUST_VERSION}-x86_64-unknown-linux-musl.tar.gz /tmp/just.tar.gz
RUN tar -xzf /tmp/just.tar.gz -C /usr/local/bin just \
    && rm /tmp/just.tar.gz

RUN corepack enable && corepack install --global pnpm@${PNPM_VERSION}
